# Generated by Django 5.2.6 on 2025-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
