# Generated by Django 5.2.6 on 2025-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('womens', 'Womens'), ('mens', 'Mens'), ('kids', 'Kids'), ('brands', 'Brands'), ('offers', 'Offers')], max_length=20)),
                ('image', models.URLField()),
                ('rating', models.IntegerField(default=0)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colors', models.JSONField(default=list)),
            ],
        ),
    ]
